version: '3.8'

services:
  app:
    image: tgeld/tgeld:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tgeld
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tgeld
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
