name: Build Validation

on:
  pull_request:
    branches: [main, development]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.archive/**'
  push:
    branches: [development]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.archive/**'

jobs:
  validate-build:
    runs-on: ubuntu-latest
    name: Validate Production Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx next lint

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Test production build
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true

      - name: Build validation summary
        if: success()
        run: |
          echo "✅ Build Validation Passed!"
          echo "- TypeScript compilation: ✅"
          echo "- ESLint validation: ✅" 
          echo "- Prettier formatting: ✅"
          echo "- Production build: ✅"
          echo ""
          echo "This PR is ready for merge! 🚀"

      - name: Build validation failure
        if: failure()
        run: |
          echo "❌ Build Validation Failed!"
          echo ""
          echo "To fix locally, run:"
          echo "  npm run build:test"
          echo ""
          echo "This will catch the same errors you're seeing in CI/CD."
          exit 1
